export const {
  CREATE_NEW_PASSWORD,
  FORGOT_PASSWORD,
  HOME,
  PRIVACY_POLICY,
  PROFILE,
  PROFILE_SETTINGS,
  SIGN_IN,
  SIGN_UP,
  TERMS_OF_SERVICE,
} = {
  CREATE_NEW_PASSWORD: '/auth/create-new-password',
  FORGOT_PASSWORD: '/auth/forgot-password',
  HOME: '/profile/userId',
  PRIVACY_POLICY: '/privacy-policy',
  PROFILE: '/profile/userId',
  PROFILE_SETTINGS: '/profile/settings',
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  TERMS_OF_SERVICE: '/terms-of-service',
} as const
