export const {
  ACCOUNT_MANAGEMENT,
  ALL_PUBLIC_POSTS,
  CREATE_NEW_PASSWORD,
  FORGOT_PASSWORD,
  HOME,
  PRIVACY_POLICY,
  PROFILE,
  PROFILE_SETTINGS,
  PUBLIC_PAGE,
  SIGN_IN,
  SIGN_UP,
  TERMS_OF_SERVICE,
} = {
  ACCOUNT_MANAGEMENT: '/profile/settings?account-management',
  ALL_PUBLIC_POSTS: '/public-posts/all',
  CREATE_NEW_PASSWORD: '/auth/create-new-password',
  FORGOT_PASSWORD: '/auth/forgot-password',
  HOME: '/profile',
  PRIVACY_POLICY: '/privacy-policy',
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PUBLIC_PAGE: '/public-page',
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  TERMS_OF_SERVICE: '/terms-of-service',
} as const
